import React from 'react';
import './App.css';
import Hobbies from './components/Hobbies';

function App() {
  return (
    <div className="container">
    <h2 className="top-head">Kevin's Favorite Hobbies</h2>
      <Hobbies name='Guitar' photo='https://cdn2.iconfinder.com/data/icons/hobbies-learning/64/Soccer_leisure_activity_Game_Hobbies_Learning_Boy-512.png'  description= "The guitar is a fretted musical instrument that usually has six strings.[1] It is typically played with both hands by strumming or plucking the strings with either a guitar pick or the fingers/fingernails of one hand, while simultaneously fretting (pressing the strings against the frets) with the fingers of the other hand. The sound of the vibrating strings is projected either acoustically, by means of the hollow chamber of the guitar (for an acoustic guitar), or through an electrical amplifier and a speaker.The guitar is a type of chordophone, traditionally constructed from wood and strung with either gut, nylon or steel strings and distinguished from other chordophones by its construction and tuning. The modern guitar was preceded by the gittern, the vihuela, the four-course Renaissance guitar, and the five-course baroque guitar, all of which contributed to the development of the modern six-string instrument." />
      <Hobbies name='Hiking' photo='#' description= "Hiking is an activity of moderate difficulty which involves walking across long distances generally on trails or paths . The duration of the activity varies between short half-day programs and longer itineraries of over   It is usually an activity that allows groups of different . Hiking and trekking are two terms sometimes used indistinctly . The difference between each of them is usually the duration of the specific activity . Hiking is associated with shorter programs , while trekking is used to describe longer programs of a week or more . Hiking is also a great way to immerse yourself in the culture and history of a country or area . Longer programs will take you to experience local communities and taste unique local food . Hiking is where the trail meets the people , and mountain sports meet cultural adventure" />
      <Hobbies name='Soccer' photo='#' description= "Football (or soccer as the game is called in some parts of the world) has a long history. Football in its current form arose in England in the middle of the 19th century. But alternative versions of the game existed much earlier and are a part of the football history. Early history and the precursors of football.The first known examples of a team game involving a ball, which was made out of a rock, occurred in old Mesoamerican cultures for over 3,000 years ago. According to the sources, the ball would symbolize the sun and the captain of the losing team would be sacrificed to the gods. The first known ball game which also involved kicking took place In China in the 3rd and 2nd century BC under the name Cuju. Cuju was played with a round ball on an area of a square. It later spread to Japan and was practiced under ceremonial forms.Other earlier variety of ball games had been known from Ancient Greece. The ball was made by shreds of leather filled with hair (the first documents of balls filled with air are from the 7th century). In the Ancient Rome, games with balls were not included in the entertainment on the big arenas, but could occur in exercises in the military. It was the Roman culture that would bring football to the British island (Britannica). It is, however, uncertain in which degree the British people were influenced by this variety and in which degree they had developed their own variants. " />
    </div>
  );
}

export default App;
